apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: us.gcr.io/glass-arcanum-424002-c3/payments
          env:
            - name: STRIPE_API_SECRET_KEY
              valueFrom:
                secretKeyRef: 
                  name: stripe-api-secret-key
                  key: STRIPE_API_SECRET_KEY
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef: 
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: MONGO_URI
              value: mongodb://payments-mongo-srv:27017/payments
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
            - name: NATS_URL
              value: http://nats-srv:4222
              

---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
